//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_comerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catalogo()
        {
            this.contratos = new HashSet<contratos>();
        }
    
        public int id_producto { get; set; }
        public string producto { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> costo { get; set; }
        public Nullable<int> capacidad { get; set; }
        public string procesador { get; set; }
        public string sistemaOperativo { get; set; }
        public string foro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contratos> contratos { get; set; }
    }
}
