//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_comerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        public int id_contrato { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_maquina { get; set; }
        public Nullable<int> id_pago { get; set; }
    
        public virtual contratos contratos1 { get; set; }
        public virtual contratos contratos2 { get; set; }
        public virtual Historico Historico { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual catalogo catalogo { get; set; }
    }
}
